### ISSUE TITLE
Resource not found - aja

### ISSUE THREAD

**Issue by tkowark** [corona-warn-app/cwa-website#28]
As noted by @Julian-B90 in [this comment](https://github.com/corona-warn-app/cwa-website/issues/6#issuecomment-637778594) the page we get a 403 for the file

https://www.coronawarn.app/assets/css/ajax-loader.gif

**Comment by ulrichstark** [comment]
There is no ajax-loader.gif in the whole repository.

"src\assets\scss\_slider.scss" requests ajax-loader-gif
```scss
.slick-list {
    padding-bottom: $spacer;

    .slick-loading & {
        background: transparent slick-image-url("ajax-loader.gif") center center no-repeat;
    }
}
```

"src\assets\scss\_variables.scss": `slick-image-url` executes `@return url($slick-loader-path + $url);` because there is no function `image-url`
```scss
@function slick-image-url($url) {
    @if function-exists(image-url) {
        @return image-url($url);
    }
    @else {
        @return url($slick-loader-path + $url);
    }
}
````

And `slick-image-url` is defined twice in 'src\assets\scss\_variables.scss' and 'src\assets\scss\_mixins.scss' but only used once for this ajax-loader.gif
