### ISSUE TITLE
Remove FAQ information for versions below minimum supported

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3238]
- This issue is related to https://github.com/corona-warn-app/cwa-website/issues/2032

## Current Implementation

The FAQs include information for all released versions.

The minimum supported versions are listed on:

https://github.com/corona-warn-app/cwa-server/blob/main/services/distribution/src/main/resources/application.yaml

```yaml
    app-versions:
      latest-ios: ${IOS_LATEST_VERSION:1.5.3}
      min-ios: ${IOS_MIN_VERSION:1.5.3}
      latest-android: ${ANDROID_LATEST_VERSION:1.0.4}
      min-android: ${ANDROID_MIN_VERSION:1.0.4}
      # With ENF v2 Android apps are versioned by Version Code and not by Semantic Versioning
      min-android-version-code: ${ANDROID_MIN_VERSION_CODE:31}
      latest-android-version-code: ${ANDROID_LATEST_VERSION_CODE:31}
```

If a user tries to run a CWA version before the minimum version they will get a message that they need to update. They cannot access any other functionality of the app until they have updated.

## Suggested Enhancement

Since it is not possible to use a CWA app which is below the minimum version, in general any information in the FAQs regarding app versions before the minimum can be removed:

Android | iOS
--- | ---
1.0.4 | 1.5.3

## Expected Benefits

Simplify the FAQ and reduce it to information relevant to app versions which can be used.
