### ISSUE TITLE
Improve testing for PR submission

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3308]
## Current Implementation

The cwa-website can be tested locally and manually using `npm test` which runs a full set of Cypress tests.

When a pull request is opened or changed then the workflow [build](https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/build.yml) is run.

On a daily basis the workflow [cypress-test-prod](https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/cypress-test-prod.yml) is run which executes a subset of Cypress tests.

The advice in [README: Testing](https://github.com/corona-warn-app/cwa-website/blob/master/README.md#testing) is as follows:

"To minimize the occurrence of errors we would ask you to perform all tests when contributing to our repository."

## Problems with current implementation

CI testing only checks that the web builds. It does not run any Cypress tests. PRs which cause the daily Cypress test to fail can be merged without any warning appearing.

`npm test` takes a long time and is flaky due to the test [cypress/e2e/hybrid/check_links.cy.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/e2e/hybrid/check_links.cy.js), which can even cause an out-of-memory browser issue when run.

Other test methods need a long string of manual commands which are not easy to remember.

## Suggested Enhancement

1. Add a new script `npm run-script test:short` to make it easier to test before creating a new PR. This should run all tests except the long-running and flaky test [cypress/e2e/hybrid/check_links.cy.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/e2e/hybrid/check_links.cy.js) which tests external links. The new test should run in the Electron browser built in to Cypress so the test can run under any of the supported operating systems (Windows, Ubuntu, macOS) without installing additional browsers.
2. Make pull requests cause a Cypress test-run to be executed. This should be the same set of tests as in `npm run-script test:short` (in other words without the external link test), running Cypress headless using the Chrome browser.<br>I suggest to add a new workflow `build-and-test` and leave the current [build](https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/build.yml) workflow in place, but disable it in the Actions menu under https://github.com/corona-warn-app/cwa-website/actions/workflows/build.yml. That way if there are problems it would be easy to switch back to the original build workflow without testing.
3. Document this in the README file.

## Expected Benefits

1. Make it easier to test before submitting PRs.<br>*On my Windows 11 desktop it took 5 minutes to complete the Cypress test of `npm run-script test:short` (alias `npm run test:short`) compared to 16 minutes to execute the full `npm run-script test` (alias `npm test`), which additionally includes the test [cypress/e2e/hybrid/check_links.cy.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/e2e/hybrid/check_links.cy.js).*
1. Reduce rework on PRs after they have been merged.
1. Increase the level of confidence to have correct PRs before they are merged.

---
Internal Tracking ID: [EXPOSUREAPP-14530](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14530)
Internal Tracking ID: [EXPOSUREAPP-14535](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14535)

**Comment by MikeMcC399** [comment]
I have submitted PR #3309 to implement a new script:

```bash
npm run test:short
```

which allows running all Cypress tests except the one for external links. It takes about 5 minutes to run.

**Comment by MikeMcC399** [comment]
Please let me know if you would also like a PR to add this test to the CI workflow triggered by `pullrequest`. I think this would be a good improvement, however I know that there were discussions in the past which declined implementing this step.

If it takes an extra 5 minutes to check a PR, that seems to be justified in terms of increased quality. None of the PRs are really time-critical. Even for new version announcements this should not be an issue - compare it with the 48 hours which Android users need to wait until an update is actually available.

**Comment by MikeMcC399** [comment]
This is what a workflow could look like:

```
name: Build and Test

on:
#  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Setup Node.js 18 environment
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/hydrogen'

    - name: Install npm dependencies
      run: npm ci

    - name: Build the website
      run: npm run-script build

    - name: Test the website
      run: npx start-server-and-test start-server http://localhost:8000 "cypress run -s 'cypress/e2e/*.js' --e2e --headless --browser chrome"
```
